spring.application.name=vetreach
spring.datasource.url=jdbc:postgresql://localhost:5432/vetreach
spring.datasource.username= postgres
spring.datasource.password=db_name
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true